### ISSUE TITLE
current working directory not handled correction

### ISSUE THREAD

**Issue by schmitts** [acorg/slurm-pipeline#34]
Using 7aabb29ac2bc6d8b7d8da34bb0e6ae601d7f1d4b and the example attached 
[cwd-issue.tar.gz](https://github.com/acorg/slurm-pipeline/files/1937949/cwd-issue.tar.gz)
I have problems with the handling of the current working directory (cwd).

```
slurm-pipeline.py -s specification.json

Traceback (most recent call last):
  File "/wang/users/sschmitt/cluster_home/projects/slurm-pipeline/bin/slurm-pipeline.py", line 87, in <module>
    startAfter=startAfter, nice=args.nice)
  File "/wang/users/sschmitt/cluster_home/projects/slurm-pipeline/slurm_pipeline/pipeline.py", line 167, in schedule
    startAfter)
  File "/wang/users/sschmitt/cluster_home/projects/slurm-pipeline/slurm_pipeline/pipeline.py", line 279, in _scheduleStep
    self._runStepScript(step, args, env)
  File "/wang/users/sschmitt/cluster_home/projects/slurm-pipeline/slurm_pipeline/pipeline.py", line 302, in _runStepScript
    stdin=DEVNULL, universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or director
```

When I remove `cwd` from the `specification.json`, the error changes to:

```
slurm-pipeline.py -s specification.json
Traceback (most recent call last):
  File "/wang/users/sschmitt/cluster_home/projects/slurm-pipeline/bin/slurm-pipeline.py", line 80, in <module>
    sp = SlurmPipeline(args.specification)
  File "/wang/users/sschmitt/cluster_home/projects/slurm-pipeline/slurm_pipeline/base.py", line 21, in __init__
    self.checkSpecification(specification)
  File "/wang/users/sschmitt/cluster_home/projects/slurm-pipeline/slurm_pipeline/pipeline.py", line 67, in checkSpecification
    (step['script'], count))
slurm_pipeline.error.SpecificationError: The script u'submit.sh' in step 1 does not exist
```

**Comment by terrycojones** [comment]
Hi. I don't see this with the current version using the files you provided:

```sh
$ slurm-pipeline.py --spec specification.json > status.json
$ slurm-pipeline-version.py
2.0.12
```

Is the original error message you posted truncated? It ends in "No such file or director".

Is it possible for you to try it with the latest version?  Also, I don't know much about spack. Can we add the latest version to it? I'd be very happy to learn how to do that if you can give me a pointer on where to start.

Thanks for the report.

**Comment by schmitts** [comment]
Sorry, it was indeed a wrongly setup environment with left-overs from previous slurm-pipeline versions. Everything works now as expected.
