### ISSUE TITLE
`slurm-pipeline-status-plot.py` fails in new (py311) conda env

### ISSUE THREAD

**Issue by imLew** [acorg/slurm-pipeline#49]
This is the error that occurs, great error message
```shell
$ slurm-pipeline-status-plot.py D_200206_16_555_4_isolate_RNA/pipelines/standard/status.json --html ffs2.html
Traceback (most recent call last):
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/bin/slurm-pipeline-status-plot.py", line 177, in <module>
    main()
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/bin/slurm-pipeline-status-plot.py", line 124, in main
    spsc = SlurmPipelineStatusCollection(args.statusFiles, names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/lib/python3.11/site-packages/slurm_pipeline/status.py", line 473, in __init__
    self.df = pd.DataFrame(
              ^^^^^^^^^^^^^
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/lib/python3.11/site-packages/pandas/core/frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 480, in dict_to_mgr
    columns = Index(keys) if keys else default_index(0)
              ^^^^^^^^^^^
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 565, in __new__
    arr = sanitize_array(data, None, dtype=dtype, copy=copy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/lib/python3.11/site-packages/pandas/core/construction.py", line 654, in sanitize_array
    subarr = maybe_convert_platform(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cephfs-1/work/projects/civ-diagnostics/packages/miniconda/envs/310/lib/python3.11/site-packages/pandas/core/dtypes/cast.py", line 139, in maybe_convert_platform
    arr = lib.maybe_convert_objects(arr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2538, in pandas._libs.lib.maybe_convert_objects
TypeError: Cannot convert numpy.ndarray to numpy.ndarray
```
The script does work in the former `310` environment.
Besides the python versions (3.9 and 3.11) the panda versions also differ, 1.3.5 vs 2.2.2.

**Comment by imLew** [comment]
Solved by removing the doubly installed numpy and reinstalled `numpy==1.26.4` (with pip).
